const data = [
  // Alimentation saine sélection de manger propre sur fond sombre. Concept d'alimentation équilibrée. Assortiment de superaliments. Vue du dessus, plan, espace de copie
  //Sélection d'aliments sains avec fruits, légumes, graines, super aliments, céréales sur fond de bois gris

  {
    lien: "/legum.png",
    title: " fruits, légumes, graines, superaliments, céréales sur fond gris",
    descreption: " very healthy   ",
    time: " 10 mint",
    price: "270.00 DA",
    priceValue: 270,
    lastPrice: "800.00 DA",
    type: "italien",
    info: "Sélection d'aliments sains avec fruits, légumes, graines, superaliments, céréales sur fond gris",
  },
  {
    lien: "/pizza italienne.png",
    title: " plats les plus appréciés",
    descreption: " very healthy   ",
    time: " 10 mint",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "300.00 DA",
    type: "pizza",
    info: "La pizza italienne est l'un des plats les plus appréciés dans le monde entier, et c'est facile à comprendre avec sa combinaison parfaite de pâte croustillante, de sauce savoureuse et de toppings frais et savoureux. Si vous voulez essayer de préparer une pizza italienne traditionnelle vous-même, lisez cet article Souvenez-vous : la clé pour réussir une pizza italienne traditionnelle est d'utiliser des ingrédients de qualité et de prendre le temps de bien pétrir (et laisser reposer) la pâte. Il est bon de noter également qu'une pâte à pizza peut être de différents types, c'est à dire qu'il est possible de préparer une pizza à partir d'une pâte filo, de feuilles de brick, et même à partir de chou-fleur si vous souhaitez une alternative healthy et vegan !",
  },
  {
    lien: "/1.png",
    title: "salad and panini",
    descreption: "very delesieuse ",
    time: "10 mint",
    price: "200,00 da",
    priceValue: 200,
    lastPrice: "850.00DA",
    type: "asiatique",
    info: " asiatique plat pour panini avec salad aussi c est une belle trop",
  },
  {
    lien: "/2.png",
    title: " big djeez",
    descreption: "so delesieuse",
    time: "09 mint",
    price: "480.00 da",
    priceValue: 480,
    type: "asiatique",
    info: " asiatique djeez pour set big  cheez --so delesieuse ",
  },
  {
    lien: "/3.png",
    title: "djeez double",
    descreption: "big djeez",
    time: "12 mint",
    price: "700.00 da",
    priceValue: 700,
    lastPrice: "30$",
    type: "asiatique",
    info: "asiatique platpour  double djeez ou big djeez  ",
  },
  {
    lien: "/7boisson.png",
    title: "boissons",
    descreption: "Cocacola",
    time: " now",
    price: "400.00 da",
    priceValue: 400,
    lastPrice: "30",
    type: "boissons",
    info: " Cocacola gazifier",
  },
  {
    lien: "/8.png",
    title: "soup vegetarien ",
    descreption: " very hot and delecieuse ",
    time: "18 mint",
    price: "400.00 da",
    priceValue: 400,
    lastPrice: "30 da",
    type: "asiatique",
    info: " soup vegetarien  very hot and delecieuse ",
  },
  {
    lien: "/pepperoni pizza.png",
    title: " PLAT PIZZA PERF 1ER CHOI ",
    descreption: "  very healthy   ",
    time: " 6 mint",
    price: "250.00 da",
    priceValue: 250,
    lastPrice: "30$",
    type: "pizza",
    info: "savoureux pepperoni pizza et ingrédients de cuisine tomates basilic sur fond de béton noir. Vue de dessus de pizza pepperoni chaud.Avec espace de copie pour le texte. Pose plate. Bannière. — Image de vasiliybudarin",
  },
  {
    lien: "/pizza3.png",
    title: " pizza fraîche",
    descreption: "  very healthy   ",
    time: " 6 mint",
    price: "250.00 da",
    priceValue: 250,
    lastPrice: "30$",
    type: "pizza",
    info: "Délicieuse pizza fraîche servie sur table en bois —",
  },

  {
    lien: "/9.png",
    title: "bourak algerien ",
    descreption: " piquon and hot ",
    time: "13 mint",
    price: "150.00 da",
    lastPrice: "150",
    lastPrice: "30",
    type: "bourak",
    info: "",
  },
  {
    lien: "/10.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "7 mint",
    price: "450.00 da",
    lastPrice: "450",
    lastPrice: "30$",
    type: "turque",
    info: "salad vegetarien  very healthy and delecieuse  ",
  },
  {
    lien: "/11fruit.png",
    title: "chiken delecieus  ",
    descreption: " healthing and delecieuse ",
    time: "16 mint",
    price: "1050.00 DA",
    lastPrice: "1050",
    lastPrice: "30$",
    type: "indien",
    info: "chiken delecieus  healthing and delecieuse  ",
  },
  {
    lien: "/bbq.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "10 mint",
    price: "100.00 da",
    lastPrice: "100",
    lastPrice: "750.00DA",
    type: "Grillades",
    info: " salad vegetarien  very healthy and delecieuse ",
  },
  {
    lien: "/bgMenu.png",
    title: " bg plat and salad vegetarien in table ",
    descreption: " very healthy and delecieuse with boissent ",
    time: "18 mint",
    price: "500.00 da",
    lastPrice: "500",
    lastPrice: "800.00DA",
    type: "italien",
    info: "bg plat and salad vegetarien in table very healthy and delecieuse with boissent ",
  },
  {
    lien: "/double.png",
    title: " double cheese burger",
    descreption: " very healthy and delicious ",
    time: " 09 mint",
    price: "500.00 DA",
    lastPrice: "500",
    lastPrice: "30$",
    type: "burger",
    info: "double cheese burger very healthy and delicious ",
  },
  {
    lien: "/fish.png",
    title: " fish with riz",
    descreption: " very healthy and delicious ",
    time: " 10mint",
    price: "600.00 DA ",
    lastPrice: "600",
    lastPrice: "30$",
    type: "asiatique",
    info: "fish with riz very healthy and delicious ",
  },
  {
    lien: "/food berger.png",
    title: " mini berger ",
    descreption: " with vegetarien  ",
    time: " 6 mint",
    price: "250.00DA",
    lastPrice: "250",
    lastPrice: "30$",
    type: "burger",
    info: "mini berger with vegetarien",
  },
  {
    lien: "/mix berger.png",
    title: " mini berger melange",
    descreption: "  very healthy   ",
    time: " 11 mint",
    price: "400.00DA",
    lastPrice: "400",
    lastPrice: "30$",
    type: "burger",
    info: "mini berger  with potatos and vegetarien and boissent",
  },

  {
    lien: "/itali.png",
    title: " aubergines grillées à l'apéritif cuites  ",
    descreption: "  very healthy   ",
    time: " 8 mint",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "italien",
    info: "Délicieuses aubergines grillées à l'apéritif cuites avec viande hachée, tomates et fromage ",
  },
  {
    lien: "/aqua fin.png",
    title: " boissent fromboise",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent de parfin Framboise et gazifier",
  },
  {
    lien: "/boissent 33cl.png",
    title: " boissent ",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  33cl cest une gazifier",
  },
  {
    lien: "/boissent cola.png",
    title: " boissent cola ",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  Cola c'est une boissent gazifier",
  },
  {
    lien: "/boissent raisin.png",
    title: " boissent raisin",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent d'une parfin de raisin cest une gazifier",
  },
  {
    lien: "/canett.png",
    title: " boissent canette",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  canette cest une gazifier",
  },
  {
    lien: "/chupa.png",
    title: " boissent chupa",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent chupa gazifier mais trop bonne",
  },
  {
    lien: "/coca 24cl.png",
    title: " boissent coca cola 24cl",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent coca cola 24cl gazifier",
  },
  {
    lien: "/coca.png",
    title: " boissent coca cola",
    descreption: "  gazifier  ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent coca cola gazifier",
  },
  {
    lien: "/fanta can.png",
    title: " boissent fanta canette",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " canette de fanta c est une gazifier",
  },
  {
    lien: "/fanta.png",
    title: " boissent de fanta",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de fanta pm gazifier",
  },
  {
    lien: "/ifriut jus.png",
    title: " jus ifruit 24cl",
    descreption: " non  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent de jus ifruit 24cl non  gazifier ",
  },
  {
    lien: "/jus rani.png",
    title: " jus de rany ",
    descreption: "  non gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " jus de rany non gazifier",
  },
  {
    lien: "/liptonTHe.png",
    title: " iceThe lipton",
    descreption: "  non gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "ice the non gazifier",
  },
  {
    lien: "/pizza.png",
    title: " Pizza maison aux champignons",
    descreption: "     ",
    time: " 10 mint",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "pizza",
    info: "Pizza maison aux champignons, oignons et bacon. Vue de dessus. espace libre pour votre texte. Style rustique ",
  },
  {
    lien: "/moon.png",
    title: " jus moon",
    descreption: " non  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent non gazifier",
  },
  {
    lien: "/orangina canet.png",
    title: " jus orangina canette",
    descreption: "  non gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent non gazifier orangina canette ",
  },
  {
    lien: "/redBul.png",
    title: " redbul energie",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "POWERADE BLEU ICE STORM BOISSON ÉNERGISANT",
  },
  {
    lien: "/rouiba jus.png",
    title: " jus ruiba 33cl",
    descreption: "  jus non gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " jus ruiba 33 cl non gazifier ",
  },
  {
    lien: "/schwepps.png",
    title: " boissent canette schwepps",
    descreption: " gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/schweps.png",
    title: " boutaille 1litre de schwepps",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/sprite 1l.png",
    title: " boissent sprite 1litre",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/azro.png",
    title: " Eau, glucose, fructose, acidifiant ",
    descreption: "  sauce sur la base dans une cuisine commerciale ",
    time: " --",
    price: "100.00 DA",
    lastPrice: "100",
    lastPrice: "300.00da",
    type: "boissent",
    info: "Boisson énergisante pour sportif,Boisson diététique de l’effort isotonique,avec sucres et édulcorants.L'info en plus : Powerade a été lancé en 1988",
  },
  {
    lien: "/pizza1.png",
    title: " pizza chef ",
    descreption: "  sauce sur la base dans une cuisine commerciale ",
    time: " --",
    price: "100.00 DA",
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "  izza chef mettre la sauce sur la base dans une cuisine commerciale ",
  },
];

export default data;
