const data = [
  {
    lien: "/pizza italienne.png",
    title: " plats les plus appréciés dans le monde entier",
    descreption: "  very healthy   ",
    time: " 10 mint",
    price: "250.00 DA",
    lastPrice: "300.00 DA",
    type: "pizza",
    Info: "La pizza italienne est l'un des plats les plus appréciés dans le monde entier, et c'est facile à comprendre avec sa combinaison parfaite de pâte croustillante, de sauce savoureuse et de toppings frais et savoureux. Si vous voulez essayer de préparer une pizza italienne traditionnelle vous-même, lisez cet article Souvenez-vous : la clé pour réussir une pizza italienne traditionnelle est d'utiliser des ingrédients de qualité et de prendre le temps de bien pétrir (et laisser reposer) la pâte. Il est bon de noter également qu'une pâte à pizza peut être de différents types, c'est à dire qu'il est possible de préparer une pizza à partir d'une pâte filo, de feuilles de brick, et même à partir de chou-fleur si vous souhaitez une alternative healthy et vegan !",
  },
  {
    lien: "/1.png",
    title: "salad and panini",
    descreption: "very delesieuse ",
    time: "10 mint",
    price: "02 €",
    lastPrice: "850.00DA",
    type: "asiatique",
    info: "",
  },
  {
    lien: "/2.png",
    title: " big djeez",
    descreption: "so delesieuse",
    time: "09 mint",
    price: "480.00DA",
    lastPrice: "30$",
    type: "asiatique",
    info: "",
  },
  {
    lien: "/3.png",
    title: "djeez double",
    descreption: "big djeez",
    time: "12 mint",
    price: "700.00DA",
    lastPrice: "30$",
    type: "asiatique",
    info: "",
  },
  {
    lien: "/7boisson.png",
    title: "boissons",
    descreption: "Cocacola",
    time: " now",
    price: "400.00DA",
    lastPrice: "30$",
    type: "boissons",
    info: "",
  },
  {
    lien: "/8.png",
    title: "soup vegetarien ",
    descreption: " very hot and delecieuse ",
    time: "18 mint",
    price: "400.00DA",
    lastPrice: "30$",
    type: "asiatique",
    info: "",
  },
  {
    lien: "/pepperoni pizza.png",
    title: " PLAT PIZZA PERF MTA9EB 79-3 1ER CHOI ",
    descreption: "  very healthy   ",
    time: " 6 mint",
    price: "250.00 DA",
    lastPrice: "30$",
    type: "pizza",
    Info: "savoureux pepperoni pizza et ingrédients de cuisine tomates basilic sur fond de béton noir. Vue de dessus de pizza pepperoni chaud.Avec espace de copie pour le texte. Pose plate. Bannière. — Image de vasiliybudarin",
  },
  {
    lien: "/9.png",
    title: "bourak algerien ",
    descreption: " piquon and hot ",
    time: "13 mint",
    price: "150.00DA",
    lastPrice: "30$",
    type: "bourak",
    info: "",
  },
  {
    lien: "/10.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "7 mint",
    price: "450.00DA",
    lastPrice: "30$",
    type: "turque",
    info: "",
  },
  {
    lien: "/11fruit.png",
    title: "chiken delecieus  ",
    descreption: " healthing and delecieuse ",
    time: "16 mint",
    price: "1050.00DA",
    lastPrice: "30$",
    type: "indien",
    info: "",
  },
  {
    lien: "/bbq.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "10 mint",
    price: "1.01 $",
    lastPrice: "750.00DA",
    type: "Grillades",
    info: "",
  },
  {
    lien: "/bgMenu.png",
    title: " bg plat and salad vegetarien in table ",
    descreption: " very healthy and delecieuse with boissent ",
    time: "18 mint",
    price: "5.08 $",
    lastPrice: "800.00DA",
    type: "italien",
    info: "",
  },
  {
    lien: "/double.png",
    title: " double cheese burger",
    descreption: " very healthy and delicious ",
    time: " 09 mint",
    price: "500.00 DA",
    lastPrice: "30$",
    type: "burger",
  },
  {
    lien: "/fish.png",
    title: " fish with riz",
    descreption: " very healthy and delicious ",
    time: " 10mint",
    price: "600.00DA ",
    lastPrice: "30$",
    type: "asiatique",
    info: "",
  },
  {
    lien: "/food berger.png",
    title: " mini berger ",
    descreption: " with vegetarien  ",
    time: " 6 mint",
    price: "250.00DA",
    lastPrice: "30$",
    type: "berger",
    info: "",
  },
  {
    lien: "/mix berger.png",
    title: " mini berger  with potatos and vegetarien and boissent",
    descreption: "  very healthy   ",
    time: " 11 mint",
    price: "400.00DA",
    lastPrice: "30$",
    type: "berger",
    info: "Mimiuo Pelle à Pizza en bambou",
  },
  {
    lien: "/mix berger.png",
    title: " PLAT PIZZA PERF MTA9EB 79-3 1ER CHOI ",
    descreption: "  very healthy   ",
    time: " 8 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "berger",
    info: "",
  },
  {
    lien: "/aqua fin.png",
    title: " boissent fromboise",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/boissent 33cl.png",
    title: " boissent ",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/boissent cola.png",
    title: " boissent cola ",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/boissent raisin.png",
    title: " boissent raisin",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/canett.png",
    title: " boissent canette",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/chupa.png",
    title: " boissent chupa",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/coca 24cl.png",
    title: " boissent coca cola 24cl",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/coca.png",
    title: " boissent coca cola",
    descreption: "  very healthy   ",
    "": " 4 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/fanta can.png",
    title: " boissent fanta canette",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/fanta.png",
    title: " boissent de fanta",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/ifriut jus.png",
    title: " jus ifruit 24cl",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/jus rani.png",
    title: " jus de rany ",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/liptonTHe.png",
    title: " iceThe lipton",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/moon.png",
    title: " jus moon",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/orangina canet.png",
    title: " jus orangina canette",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/redBul.png",
    title: " redbul energie",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "POWERADE BLEU ICE STORM BOISSON ÉNERGISANT"
  },
  {
    lien: "/rouiba jus.png",
    title: " jus ruiba 33cl",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/schwepps.png",
    title: " boissent canette schwepps",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/schweps.png",
    title: " boutaille 1litre de schwepps",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    lien: "/sprite 1l.png",
    title: " boissent sprite 1litre",
    descreption: "  very healthy   ",
    "": " 6 mint",
    price: "250.00 DA",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
];

export default data;
