const data = [
  // Alimentation saine sélection de manger propre sur fond sombre. Concept d'alimentation équilibrée. Assortiment de superaliments. Vue du dessus, plan, espace de copie
  //Sélection d'aliments sains avec fruits, légumes, graines, super aliments, céréales sur fond de bois gris

  {
    name: "legume",
    lien: "/legum.png",
    title: " fruits, légumes, graines, superaliments, céréales sur fond gris",
    descreption: " very healthy   ",
    time: " 10 mint",
    price: "270.00 DA",
    priceValue: 270,
    lastPrice: "800.00 DA",
    type: "italien",
    info: "Sélection d'aliments sains avec fruits, légumes, graines, superaliments, céréales sur fond gris",
  },
  {
    name: " pizza italienne",
    lien: "/pizza italienne.png",
    title: " plats les plus appréciés",
    descreption: " very healthy   ",
    time: " 10 mint",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "300.00 DA",
    type: "pizza",
    info: "La pizza italienne est l'un des plats les plus appréciés dans le monde entier, et c'est facile à comprendre avec sa combinaison parfaite de pâte croustillante, de sauce savoureuse ",
  },
  {
    name: "panini et legume ",
    lien: "/1.png",
    title: "salad and panini",
    descreption: "very delesieuse ",
    time: "10 mint",
    price: "200,00 da",
    priceValue: 200,
    lastPrice: "850.00DA",
    type: "asiatique",
    info: " asiatique plat pour panini avec salad aussi c est une belle trop",
  },
  {
    name: "big cheez",
    lien: "/2.png",
    title: " big djeez",
    descreption: "so delesieuse",
    time: "09 mint",
    price: "480.00 da",
    priceValue: 480,
    type: "asiatique",
    info: " asiatique djeez pour set big  cheez --so delesieuse ",
  },
  {
    name: "cheez doublee",
    lien: "/3.png",
    title: "djeez double",
    descreption: "big djeez",
    time: "12 mint",
    price: "700.00 da",
    priceValue: 700,
    lastPrice: "30$",
    type: "asiatique",
    info: "asiatique platpour  double djeez ou big djeez  ",
  },
  {
    name: "jus press raisin",
    lien: "/7boisson.png",
    title: "boissons",
    descreption: "Cocacola",
    time: " now",
    price: "400.00 da",
    priceValue: 400,
    lastPrice: "30",
    type: "boissons",
    info: " ju presser de parfin raisin c est non gazifier son tres bon got",
  },
  {
    name: "soup vegetarien",
    lien: "/8.png",
    title: "soup vegetarien ",
    descreption: " very hot and delecieuse ",
    time: "18 mint",
    price: "400.00 da",
    priceValue: 400,
    lastPrice: "30 da",
    type: "asiatique",
    info: " soup vegetarien  et poulet et mix de ris et poichich very hot and delecieuse ",
  },
  {
    name: "pepperoni pizza ",
    lien: "/pepperoni pizza.png",
    title: " PLAT PIZZA PERF 1ER CHOI ",
    descreption: "  very healthy   ",
    time: " 6 mint",
    price: "250.00 da",
    priceValue: 250,
    lastPrice: "30$",
    type: "pizza",
    info: "savoureux pepperoni pizza et ingrédients de cuisine tomates basilic sur fond de béton noir. Vue de dessus de pizza pepperoni chaud.Avec espace de copie pour le texte. Pose plate. Bannière. — Image de vasiliybudarin",
  },
  {
    name: "pizza fraîche",
    lien: "/pizza3.png",
    title: " pizza fraîche",
    descreption: "  very healthy   ",
    time: " 6 mint",
    price: "250.00 da",
    priceValue: 250,
    lastPrice: "30$",
    type: "pizza",
    info: "Délicieuse pizza fraîche servie sur table en bois —",
  },

  {
    name: "bourak",
    lien: "/9.png",
    title: "bourak algerien ",
    descreption: " piquon and hot ",
    time: "13 mint",
    price: "150.00 da",
    lastPrice: "150",
    priceValue: 150,
    lastPrice: "30",
    type: "bourak",
    info: " so sweet eat the is the best eating",
  },
  {
    name: "salad vegetarien",
    lien: "/10.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "7 mint",
    price: "450.00 da",
    lastPrice: "450",
    priceValue: 450,
    lastPrice: "30$",
    type: "turque",
    info: "salad vegetarien  very healthy and delecieuse  ",
  },
  {
    name: "chiken delecieus ",
    lien: "/11fruit.png",
    title: "chiken delecieus  ",
    descreption: " healthing and delecieuse ",
    time: "16 mint",
    price: "1050.00 DA",
    priceValue: 1050,
    lastPrice: "1050",
    lastPrice: "30$",
    type: "indien",
    info: "chiken delecieus  healthing and delecieuse  ",
  },
  {
    name: " salad vegetarien",
    lien: "/bbq.png",
    title: "salad vegetarien ",
    descreption: " very healthy and delecieuse ",
    time: "10 mint",
    price: "100.00 da",
    priceValue: 100,
    lastPrice: "100",
    lastPrice: "750.00DA",
    type: "Grillades",
    info: " salad vegetarien  very healthy and delecieuse ",
  },
  {
    name: "big plat vegetarien ",
    lien: "/bgMenu.png",
    title: " bg plat and salad vegetarien in table ",
    descreption: " very healthy and delecieuse with boissent ",
    time: "18 mint",
    price: "500.00 da",
    priceValue: 500,
    lastPrice: "500",
    lastPrice: "800.00DA",
    type: "italien",
    info: "bg plat and salad vegetarien in table very healthy and delecieuse with boissent ",
  },
  {
    name: "burger doublee",
    lien: "/double.png",
    title: " double cheese burger",
    descreption: " very healthy and delicious ",
    time: " 09 mint",
    price: "500.00 DA",
    priceValue: 500,
    lastPrice: "500",
    lastPrice: "30$",
    type: "burger",
    info: "double cheese burger very healthy and delicious ",
  },
  {
    name: "fich et riz",
    lien: "/fish.png",
    title: " fish with riz",
    descreption: " very healthy and delicious ",
    time: " 10mint",
    price: "600.00 DA ",
    priceValue: 600,
    lastPrice: "600",
    lastPrice: "30$",
    type: "asiatique",
    info: "fish with riz very healthy and delicious ",
  },
  {
    name: "mini burger",
    lien: "/food berger.png",
    title: " mini berger ",
    descreption: " with vegetarien  ",
    time: " 6 mint",
    price: "250.00DA",
    priceValue: 250,
    lastPrice: "250",
    lastPrice: "30$",
    type: "burger",
    info: "mini berger with vegetarien",
  },
  {
    name: "burger melange",
    lien: "/mix berger.png",
    title: " mini berger melange",
    descreption: "  very healthy   ",
    time: " 11 mint",
    price: "400.00DA",
    priceValue: 400,
    lastPrice: "400",
    lastPrice: "30$",
    type: "burger",
    info: "mini berger  with potatos and vegetarien and boissent",
  },

  {
    name: " aubergines grillées",
    name: "mini burger",
    lien: "/itali.png",
    title: " aubergines grillées à l'apéritif cuites  ",
    descreption: "  very healthy   ",
    time: " 8 mint",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "italien",
    info: "Délicieuses aubergines grillées à l'apéritif cuites avec viande hachée, tomates et fromage ",
  },
  {
    name: "boissent Framboise",
    lien: "/aqua fin.png",
    title: " boissent fromboise",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent de parfin Framboise et gazifier",
  },
  {
    name: "boissent sanpilicrino",
    lien: "/boissent 33cl.png",
    title: " boissent ",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  33cl cest une gazifier",
  },
  {
    name: "cola boissent",
    lien: "/boissent cola.png",
    title: " boissent cola ",
    descreption: "  gazifier   ",
    time: " --",
    price: "250.00 DA",
    priceValue: 250,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  Cola c'est une boissent gazifier",
  },
  {
    name: "boissent raisin",
    lien: "/boissent raisin.png",
    title: " boissent raisin",
    descreption: "  gazifier   ",
    time: " --",
    price: "700.00 DA",
    priceValue: 700,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent d'une parfin de raisin cest une gazifier",
  },
  {
    name: "canett",
    lien: "/canett.png",
    title: " boissent canette",
    descreption: "  gazifier   ",
    time: " --",
    price: "350.00 DA",
    priceValue: 350,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de  canette cest une gazifier",
  },
  {
    name: "boissent chupa",
    lien: "/chupa.png",
    title: " boissent chupa",
    descreption: "  gazifier   ",
    time: " --",
    price: "340.00 DA",
    priceValue: 340,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent chupa gazifier mais trop bonne",
  },
  {
    name: "coca 24cl",
    lien: "/coca 24cl.png",
    title: " boissent coca cola 24cl",
    descreption: "  gazifier   ",
    time: " --",
    price: "430.00 DA",
    priceValue: 430,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent coca cola 24cl gazifier",
  },
  {
    name: "coca",
    lien: "/coca.png",
    title: " boissent coca cola",
    descreption: "  gazifier  ",
    time: " --",
    price: "410.00 DA",
    priceValue: 410,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent coca cola gazifier",
  },
  {
    name: "fanta can",
    lien: "/fanta can.png",
    title: " boissent fanta canette",
    descreption: "  gazifier   ",
    time: " --",
    price: "510.00 DA",
    priceValue: 510,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " canette de fanta c est une gazifier",
  },
  {
    name: "fanta ",
    lien: "/fanta.png",
    title: " boissent de fanta",
    descreption: "  gazifier   ",
    time: " --",
    price: "390.00 DA",
    priceValue: 390,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent de fanta pm gazifier",
  },
  {
    name: "ifruit jus",
    lien: "/ifriut jus.png",
    title: " jus ifruit 24cl",
    descreption: " non  gazifier   ",
    time: " --",
    price: "380.00 DA",
    priceValue: 380,
    lastPrice: "300.00da",
    type: "boissent",
    info: "boissent de jus ifruit 24cl non  gazifier ",
  },
  {
    name: "jus rani",
    lien: "/jus rani.png",
    title: " jus de rany ",
    descreption: "  non gazifier   ",
    time: " --",
    price: "370.00 DA",
    priceValue: 370,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " jus de rany non gazifier",
  },
  {
    name: "Lipton",
    lien: "/liptonTHe.png",
    title: " iceThe lipton",
    descreption: "  non gazifier   ",
    time: " --",
    price: "360.00 DA",
    priceValue: 360,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "ice the non gazifier",
  },
  {
    name: "pizza maison",
    lien: "/pizza.png",
    title: " Pizza maison aux champignons",
    descreption: "     ",
    time: " 10 mint",
    price: "350.00 DA",
    priceValue: 350,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "pizza",
    info: "Pizza maison aux champignons, oignons et bacon. Vue de dessus. espace libre pour votre texte. Style rustique ",
  },
  {
    name: "jus moon",
    lien: "/moon.png",
    title: " jus moon",
    descreption: " non  gazifier   ",
    time: " --",
    price: "340.00 DA",
    priceValue: 340,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent non gazifier",
  },
  {
    name: "orangina",
    lien: "/orangina canet.png",
    title: " jus orangina canette",
    descreption: "  non gazifier   ",
    time: " --",
    price: "330.00 DA",
    priceValue: 330,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: " boissent non gazifier orangina canette ",
  },
  {
    name: "redbul",
    lien: "/redBul.png",
    title: " redbul energie",
    descreption: "  gazifier   ",
    time: " --",
    price: "320.00 DA",
    priceValue: 320,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "POWERADE BLEU ICE STORM BOISSON ÉNERGISANT",
  },
  {
    name: "ruiba jus",
    lien: "/rouiba jus.png",
    title: " jus ruiba 33cl",
    descreption: "  jus non gazifier   ",
    time: " --",
    price: "400.00 DA",
    priceValue: 400,
    lastPrice: "440",
    lastPrice: "300.00da",
    type: "boissent",
    info: " jus ruiba 33 cl non gazifier ",
  },
  {
    name: "schupa",
    lien: "/schwepps.png",
    title: " boissent canette schwepps",
    descreption: " gazifier   ",
    time: " --",
    price: "410.00 DA",
    priceValue: 410,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    name: "schupa 1l",
    lien: "/schweps.png",
    title: " boutaille 1litre de schwepps",
    descreption: "  gazifier   ",
    time: " --",
    price: "420.00 DA",
    priceValue: 420,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    name: "sprite 1l",
    lien: "/sprite 1l.png",
    title: " boissent sprite 1litre",
    descreption: "  gazifier   ",
    time: " --",
    price: "430.00 DA",
    priceValue: 430,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "boissent",
    info: "",
  },
  {
    name: "azro",
    lien: "/azro.png",
    title: " Eau, glucose, fructose, acidifiant ",
    descreption: "  sauce sur la base dans une cuisine commerciale ",
    time: " --",
    price: "480.00 DA",
    priceValue: 480,
    lastPrice: "100",
    lastPrice: "300.00da",
    type: "boissent",
    info: "Boisson énergisante pour sportif,Boisson diététique de l’effort isotonique,avec sucres et édulcorants.L'info en plus : Powerade a été lancé en 1988",
  },
  {
    name: "pizza chef",
    lien: "/pizza1.png",
    title: " pizza chef ",
    descreption: "  sauce sur la base dans une cuisine commerciale ",
    time: " --",
    price: "550.00 DA",
    priceValue: 550,
    lastPrice: "250",
    lastPrice: "300.00da",
    type: "pizza",
    info: "  izza chef mettre la sauce sur la base dans une cuisine commerciale ",
  },
];

export default data;
